public struct EPAResponse:Codable {
    public var spectraResponse:[SpectraResponse]?
    public var pscompparsResponse:[PscompparsResponse]?
    public var superwasptimeseriesResponse:[SuperwasptimeseriesResponse]?
    public var kelttimeseriesResponse:[KelttimeseriesResponse]?
    public var stellarhostsResponse:[StellarhostsResponse]?
    public var transitspecResponse:[TransitspecResponse]?
    public var emissionspecResponse:[EmissionspecResponse]?
    public var psResponse:[PsResponse]?
    public var keplernamesResponse:[KeplernamesResponse]?
    public var k2namesResponse:[K2namesResponse]?
    public var toiResponse:[ToiResponse]?
    public var ukirttimeseriesResponse:[UkirttimeseriesResponse]?
    public var mlResponse:[MlResponse]?
    public var object_aliasesResponse:[Object_aliasesResponse]?

    
    public mutating func setSpectraResponse(_ spectraResponse: [SpectraResponse]) {
    self.spectraResponse = spectraResponse
    }
    
    public mutating func setPscompparsResponse(_ pscompparsResponse: [PscompparsResponse]) {
    self.pscompparsResponse = pscompparsResponse
    }
    
    public mutating func setSuperwasptimeseriesResponse(_ superwasptimeseriesResponse: [SuperwasptimeseriesResponse]) {
    self.superwasptimeseriesResponse = superwasptimeseriesResponse
    }
    
    public mutating func setKelttimeseriesResponse(_ kelttimeseriesResponse: [KelttimeseriesResponse]) {
    self.kelttimeseriesResponse = kelttimeseriesResponse
    }
    
    public mutating func setStellarhostsResponse(_ stellarhostsResponse: [StellarhostsResponse]) {
    self.stellarhostsResponse = stellarhostsResponse
    }
    
    public mutating func setTransitspecResponse(_ transitspecResponse: [TransitspecResponse]) {
    self.transitspecResponse = transitspecResponse
    }
    
    public mutating func setEmissionspecResponse(_ emissionspecResponse: [EmissionspecResponse]) {
    self.emissionspecResponse = emissionspecResponse
    }
    
    public mutating func setPsResponse(_ psResponse: [PsResponse]) {
    self.psResponse = psResponse
    }
    
    public mutating func setKeplernamesResponse(_ keplernamesResponse: [KeplernamesResponse]) {
    self.keplernamesResponse = keplernamesResponse
    }
    
    public mutating func setK2namesResponse(_ k2namesResponse: [K2namesResponse]) {
    self.k2namesResponse = k2namesResponse
    }
    
    public mutating func setToiResponse(_ toiResponse: [ToiResponse]) {
    self.toiResponse = toiResponse
    }
    
    public mutating func setUkirttimeseriesResponse(_ ukirttimeseriesResponse: [UkirttimeseriesResponse]) {
    self.ukirttimeseriesResponse = ukirttimeseriesResponse
    }
    
    public mutating func setMlResponse(_ mlResponse: [MlResponse]) {
    self.mlResponse = mlResponse
    }
    
    public mutating func setObject_aliasesResponse(_ object_aliasesResponse: [Object_aliasesResponse]) {
    self.object_aliasesResponse = object_aliasesResponse
    }

}


public struct SpectraResponse:Codable {
var pl_name:String?
var spec_type:String?
var authors:String?
var num_datapoints:Int?
var instrument:String?
var facility:String?
var mintranmid:Double?
var maxtranmid:Double?
var minwavelng:Double?
var maxwavelng:Double?
var note:String?
var bibcode:String?
var spec_path:String?
}

public struct PscompparsResponse:Codable {
var pl_orbeccenstr:String?
var pl_orbeccen_reflink:String?
var pl_eqt:Double?
var pl_eqterr1:Double?
var pl_eqterr2:Double?
var pl_eqtlim:Int?
var pl_eqt_reflink:String?
var pl_eqtstr:String?
var pl_occdep:Double?
var pl_occdeperr1:Double?
var pl_occdeperr2:Double?
var pl_occdeplim:Int?
var pl_occdep_reflink:String?
var pl_occdepstr:String?
var pl_insol:Double?
var pl_insolerr1:Double?
var pl_insolerr2:Double?
var pl_insollim:Int?
var pl_insolstr:String?
var pl_insol_reflink:String?
var pl_dens:Double?
var pl_denserr1:Double?
var pl_denserr2:Double?
var pl_denslim:Int?
var pl_dens_reflink:String?
var pl_densstr:String?
var pl_trandep:Double?
var pl_trandeperr1:Double?
var pl_trandeperr2:Double?
var pl_trandeplim:Int?
var pl_trandepstr:String?
var pl_trandep_reflink:String?
var pl_tranmid:Double?
var pl_tranmiderr1:Double?
var pl_tranmiderr2:Double?
var pl_tranmidlim:Int?
var pl_angsep_reflink:String?
var pl_tranmidstr:String?
var pl_tranmid_reflink:String?
var pl_trandur:Double?
var pl_trandurerr1:Double?
var pl_trandurerr2:Double?
var pl_trandurlim:Int?
var pl_trandurstr:String?
var pl_trandur_reflink:String?
var pl_rvamp:Double?
var pl_rvamperr1:Double?
var pl_rvamperr2:Double?
var pl_rvamplim:Int?
var pl_rvampstr:String?
var pl_rvamp_reflink:String?
var pl_radj:Double?
var pl_radjerr1:Double?
var pl_radjerr2:Double?
var pl_radjlim:Int?
var pl_radjstr:String?
var pl_radj_reflink:String?
var pl_rade:Double?
var pl_radeerr1:Double?
var pl_radeerr2:Double?
var pl_radelim:Int?
var pl_radestr:String?
var pl_rade_reflink:String?
var pl_ratror:Double?
var pl_ratrorerr1:Double?
var pl_ratrorerr2:Double?
var pl_ratrorlim:Int?
var pl_ratrorstr:String?
var pl_ratror_reflink:String?
var pl_ratdor:Double?
var pl_ratdorerr1:Double?
var pl_ratdorerr2:Double?
var pl_ratdorlim:Int?
var pl_ratdorstr:String?
var pl_ratdor_reflink:String?
var pl_imppar:Double?
var pl_impparerr1:Double?
var pl_impparerr2:Double?
var pl_impparlim:Int?
var pl_impparstr:String?
var pl_imppar_reflink:String?
var pl_bmassj:Double?
var pl_bmassjerr1:Double?
var pl_bmassjerr2:Double?
var pl_bmassjlim:Int?
var pl_bmassjstr:String?
var pl_bmassj_reflink:String?
var pl_bmasse:Double?
var pl_bmasseerr1:Double?
var pl_bmasseerr2:Double?
var pl_bmasselim:Int?
var pl_bmassestr:String?
var pl_bmasse_reflink:String?
var pl_bmassprov:String?
var st_teff:Double?
var st_tefferr1:Double?
var st_tefferr2:Double?
var st_tefflim:Int?
var st_teffstr:String?
var st_teff_reflink:String?
var st_met:Double?
var st_meterr1:Double?
var st_meterr2:Double?
var st_metlim:Int?
var st_metstr:String?
var st_met_reflink:String?
var st_radv:Double?
var st_radverr1:Double?
var st_radverr2:Double?
var st_radvlim:Int?
var st_radvstr:String?
var st_radv_reflink:String?
var st_vsin:Double?
var st_vsinerr1:Double?
var st_vsinerr2:Double?
var st_vsinlim:Int?
var st_vsinstr:String?
var st_vsin_reflink:String?
var st_lum:Double?
var st_lumerr1:Double?
var st_lumerr2:Double?
var st_lumlim:Int?
var st_lumstr:String?
var st_lum_reflink:String?
var st_logg:Double?
var st_loggerr1:Double?
var st_loggerr2:Double?
var st_logglim:Int?
var st_loggstr:String?
var st_logg_reflink:String?
var st_age:Double?
var st_ageerr1:Double?
var st_ageerr2:Double?
var st_agelim:Int?
var st_agestr:String?
var st_age_reflink:String?
var st_mass:Double?
var st_masserr1:Double?
var st_masserr2:Double?
var st_masslim:Int?
var st_massstr:String?
var st_mass_reflink:String?
var st_dens:Double?
var st_denserr1:Double?
var st_denserr2:Double?
var st_denslim:Int?
var st_densstr:String?
var st_dens_reflink:String?
var st_rad:Double?
var st_raderr1:Double?
var st_raderr2:Double?
var st_radlim:Int?
var st_radstr:String?
var st_rad_reflink:String?
var ttv_flag:Int?
var ptv_flag:Int?
var tran_flag:Int?
var rv_flag:Int?
var ast_flag:Int?
var obm_flag:Int?
var micro_flag:Int?
var etv_flag:Int?
var ima_flag:Int?
var pul_flag:Int?
var sy_snum:Int?
var sy_pnum:Int?
var sy_mnum:Int?
var st_nphot:Int?
var st_nrvc:Int?
var st_nspec:Int?
var pl_nnotes:Int?
var pl_ntranspec:Int?
var pl_nespec:Int?
var pl_ndispec:Int?
var sy_pm:Double?
var sy_pmerr1:Double?
var sy_pmerr2:Double?
var sy_pmstr:String?
var sy_pm_reflink:String?
var sy_pmra:Double?
var sy_pmraerr1:Double?
var sy_pmraerr2:Double?
var sy_pmrastr:String?
var sy_pmdec:Double?
var sy_pmdecerr1:Double?
var sy_pmdecerr2:Double?
var sy_pmdecstr:String?
var sy_plx:Double?
var sy_plxerr1:Double?
var sy_plxerr2:Double?
var sy_plxstr:String?
var sy_plx_reflink:String?
var sy_dist:Double?
var sy_disterr1:Double?
var sy_disterr2:Double?
var sy_diststr:String?
var sy_dist_reflink:String?
var sy_bmag:Double?
var sy_bmagerr1:Double?
var sy_bmagerr2:Double?
var sy_bmagstr:String?
var sy_bmag_reflink:String?
var sy_vmag:Double?
var sy_vmagerr1:Double?
var sy_vmagerr2:Double?
var sy_vmagstr:String?
var sy_vmag_reflink:String?
var sy_jmag:Double?
var sy_jmagerr1:Double?
var sy_jmagerr2:Double?
var sy_jmagstr:String?
var sy_jmag_reflink:String?
var sy_hmag:Double?
var sy_hmagerr1:Double?
var sy_hmagerr2:Double?
var sy_hmag_reflink:String?
var sy_hmagstr:String?
var sy_kmag:Double?
var sy_kmagerr1:Double?
var sy_kmagerr2:Double?
var sy_kmag_reflink:String?
var sy_kmagstr:String?
var sy_umag:Double?
var sy_umagerr1:Double?
var sy_umagerr2:Double?
var sy_umag_reflink:String?
var sy_umagstr:String?
var sy_rmag:Double?
var sy_rmagerr1:Double?
var sy_rmagerr2:Double?
var sy_rmag_reflink:String?
var sy_rmagstr:String?
var sy_imag:Double?
var sy_imagerr1:Double?
var sy_imagerr2:Double?
var sy_imag_reflink:String?
var sy_imagstr:String?
var sy_zmag:Double?
var sy_zmagerr1:Double?
var sy_zmagerr2:Double?
var sy_zmag_reflink:String?
var sy_zmagstr:String?
var sy_w1mag:Double?
var sy_w1magerr1:Double?
var sy_w1magerr2:Double?
var sy_w1mag_reflink:String?
var sy_w1magstr:String?
var sy_w2mag:Double?
var sy_w2magerr1:Double?
var sy_w2magerr2:Double?
var sy_w2mag_reflink:String?
var sy_w2magstr:String?
var sy_w3mag:Double?
var sy_w3magerr1:Double?
var sy_w3magerr2:Double?
var sy_w3mag_reflink:String?
var sy_w3magstr:String?
var sy_w4mag:Double?
var sy_w4magerr1:Double?
var sy_w4magerr2:Double?
var sy_w4mag_reflink:String?
var sy_w4magstr:String?
var sy_gmag:Double?
var sy_gmagerr1:Double?
var sy_gmagerr2:Double?
var sy_gmag_reflink:String?
var sy_gmagstr:String?
var sy_gaiamag:Double?
var sy_gaiamagerr1:Double?
var sy_gaiamagerr2:Double?
var sy_gaiamag_reflink:String?
var sy_gaiamagstr:String?
var sy_tmag:Double?
var sy_tmagerr1:Double?
var sy_tmagerr2:Double?
var sy_tmag_reflink:String?
var sy_tmagstr:String?
var pl_controv_flag:Int?
var pl_tranmid_systemref:String?
var pl_orbtper_systemref:String?
var st_metratio:String?
var st_spectype:String?
var sy_kepmag:Double?
var sy_kepmagerr1:Double?
var sy_kepmagerr2:Double?
var sy_kepmag_reflink:String?
var st_spectype_reflink:String?
var sy_kepmagstr:String?
var st_rotp:Double?
var st_rotperr1:Double?
var st_rotperr2:Double?
var st_rotplim:Int?
var st_rotpstr:String?
var st_rotp_reflink:String?
var pl_projobliq:Double?
var pl_projobliqerr1:Double?
var pl_projobliqerr2:Double?
var pl_projobliqlim:Int?
var pl_projobliqstr:String?
var pl_projobliq_reflink:String?
var pl_trueobliq:Double?
var x:Double?
var pl_trueobliqerr1:Double?
var y:Double?
var pl_trueobliqerr2:Double?
var z:Double?
var htm20:Int?
var pl_trueobliqlim:Int?
var gaia_id:String?
var pl_trueobliq_reflink:String?
var cb_flag:Int?
var pl_trueobliqstr:String?
var sy_icmag:Double?
var sy_icmagerr1:Double?
var sy_icmagerr2:Double?
var sy_icmagstr:String?
var sy_icmag_reflink:String?
var dkin_flag:Int?
var pl_name:String?
var pl_letter:String?
var hostname:String?
var hd_name:String?
var hip_name:String?
var tic_id:String?
var disc_pubdate:String?
var disc_year:Int?
var discoverymethod:String?
var disc_locale:String?
var disc_facility:String?
var disc_instrument:String?
var disc_telescope:String?
var disc_refname:String?
var ra:Double?
var rastr:String?
var dec:Double?
var decstr:String?
var glon:Double?
var glat:Double?
var pl_angsep:Double?
var pl_angseperr1:Double?
var pl_angseperr2:Double?
var elon:Double?
var pl_angseplim:Double?
var pl_angsepstr:String?
var elat:Double?
var pl_orbper:Double?
var pl_orbpererr1:Double?
var pl_orbpererr2:Double?
var pl_orbperlim:Int?
var pl_orbperstr:String?
var ra_reflink:String?
var pl_orbper_reflink:String?
var pl_orblpererr1:Double?
var pl_orblper:Double?
var pl_orblpererr2:Double?
var pl_orblperlim:Int?
var pl_orblperstr:String?
var pl_orblper_reflink:String?
var pl_orbsmax:Double?
var pl_orbsmaxerr1:Double?
var pl_orbsmaxerr2:Double?
var pl_orbsmaxlim:Int?
var pl_orbsmax_reflink:String?
var pl_orbsmaxstr:String?
var pl_orbincl:Double?
var pl_orbinclerr1:Double?
var pl_orbinclerr2:Double?
var pl_orbincllim:Int?
var pl_orbincl_reflink:String?
var pl_orbinclstr:String?
var pl_orbtper:Double?
var pl_orbtpererr1:Double?
var pl_orbtpererr2:Double?
var pl_orbtperlim:Int?
var pl_orbtperstr:String?
var pl_orbtper_reflink:String?
var pl_orbeccen:Double?
var pl_orbeccenerr1:Double?
var pl_orbeccenerr2:Double?
var pl_orbeccenlim:Int?
}

public struct SuperwasptimeseriesResponse:Codable {
var sourceid:String?
var obsstart:String?
var obsstop:String?
var tstart:Int?
var tstop:Int?
var hjdstart:Double?
var hjdstop:Double?
var hjd_ref:Double?
var ra:Double?
var dec:Double?
var wasp_mag:Double?
var npts:Int?
var tile:String?
var tm_statnpts:Int?
var tm_minvalue:Double?
var tm_maxvalue:Double?
var tm_mean:Double?
var tm_stddevwrtmean:Double?
var tm_median:Double?
var tm_stddevwrtmed:Double?
var tm_n5sigma:Int?
var tm_f5sigma:Double?
var tm_medabsdev:Double?
var tm_chisquared:Double?
var tm_range595:Double?
var x:Double?
var y:Double?
var z:Double?
var spt_ind:Int?
}

public struct KelttimeseriesResponse:Codable {
var kelt_sourceid:String?
var kelt_field:String?
var kelt_orientation:String?
var proc_type:String?
var kelt_proc_version:String?
var ra:Double?
var dec:Double?
var kelt_mag:Double?
var obsstart:String?
var obsstop:String?
var bjdstart:Double?
var bjdstop:Double?
var mean:Double?
var stddevwrtmean:Double?
var median:Double?
var stddevwrtmedian:Double?
var npts:Int?
var n5sigma:Int?
var f5sigma:Double?
var medabsdev:Double?
var chisquared:Double?
var range595:Double?
var minvalue:Double?
var maxvalue:Double?
var x:Double?
var y:Double?
var z:Double?
var spt_ind:Int?
}

public struct StellarhostsResponse:Codable {
var st_lum:Double?
var st_lumerr1:Double?
var st_lumerr2:Double?
var st_lumlim:Int?
var st_logg:Double?
var st_loggerr1:Double?
var st_loggerr2:Double?
var st_logglim:Int?
var st_age:Double?
var st_ageerr1:Double?
var st_ageerr2:Double?
var st_agelim:Int?
var st_mass:Double?
var st_masserr1:Double?
var st_masserr2:Double?
var st_masslim:Int?
var st_dens:Double?
var st_denserr1:Double?
var st_denserr2:Double?
var st_denslim:Int?
var st_rad:Double?
var st_raderr1:Double?
var st_raderr2:Double?
var st_radlim:Int?
var sy_snum:Int?
var sy_pnum:Int?
var sy_mnum:Int?
var sy_pm:Double?
var sy_pmerr1:Double?
var sy_pmerr2:Double?
var sy_pmra:Double?
var sy_pmraerr1:Double?
var sy_pmraerr2:Double?
var sy_pmdec:Double?
var sy_pmdecerr1:Double?
var sy_pmdecerr2:Double?
var sy_plx:Double?
var sy_plxerr1:Double?
var sy_plxerr2:Double?
var sy_dist:Double?
var sy_disterr1:Double?
var sy_disterr2:Double?
var sy_bmag:Double?
var sy_bmagerr1:Double?
var sy_bmagerr2:Double?
var sy_vmag:Double?
var sy_vmagerr1:Double?
var sy_vmagerr2:Double?
var sy_jmag:Double?
var sy_jmagerr1:Double?
var sy_jmagerr2:Double?
var sy_hmag:Double?
var sy_hmagerr1:Double?
var sy_hmagerr2:Double?
var sy_kmag:Double?
var sy_kmagerr1:Double?
var sy_kmagerr2:Double?
var sy_umag:Double?
var sy_umagerr1:Double?
var sy_umagerr2:Double?
var sy_rmag:Double?
var sy_rmagerr1:Double?
var sy_rmagerr2:Double?
var sy_imag:Double?
var sy_imagerr1:Double?
var sy_imagerr2:Double?
var sy_zmag:Double?
var sy_zmagerr1:Double?
var sy_zmagerr2:Double?
var sy_w1mag:Double?
var sy_w1magerr1:Double?
var sy_w1magerr2:Double?
var sy_w2mag:Double?
var sy_w2magerr1:Double?
var sy_w2magerr2:Double?
var sy_w3mag:Double?
var sy_w3magerr1:Double?
var sy_w3magerr2:Double?
var sy_w4mag:Double?
var sy_w4magerr1:Double?
var sy_w4magerr2:Double?
var sy_gmag:Double?
var sy_gmagerr1:Double?
var sy_gmagerr2:Double?
var sy_gaiamag:Double?
var sy_gaiamagerr1:Double?
var sy_gaiamagerr2:Double?
var sy_tmag:Double?
var sy_tmagerr1:Double?
var sy_tmagerr2:Double?
var sy_name:String?
var st_metratio:String?
var st_spectype:String?
var sy_kepmag:Double?
var sy_kepmagerr1:Double?
var sy_kepmagerr2:Double?
var st_rotp:Double?
var st_rotperr1:Double?
var st_rotperr2:Double?
var st_rotplim:Int?
var gaia_id:String?
var cb_flag:Int?
var sy_icmag:Double?
var sy_icmagerr1:Double?
var sy_icmagerr2:Double?
var hostname:String?
var hd_name:String?
var hip_name:String?
var tic_id:String?
var st_refname:String?
var sy_refname:String?
var ra:Double?
var rastr:String?
var dec:Double?
var decstr:String?
var glon:Double?
var glat:Double?
var elon:Double?
var elat:Double?
var st_teff:Double?
var st_tefferr1:Double?
var st_tefferr2:Double?
var st_tefflim:Int?
var st_met:Double?
var st_meterr1:Double?
var st_meterr2:Double?
var st_metlim:Int?
var st_radv:Double?
var st_radverr1:Double?
var st_radverr2:Double?
var st_radvlim:Int?
var st_vsin:Double?
var st_vsinerr1:Double?
var st_vsinerr2:Double?
var st_vsinlim:Int?
}

public struct TransitspecResponse:Codable {
var centralwavelng:Double?
var bandwidth:Double?
var plntransdep:Double?
var plntransdeperr1:Double?
var plntransdeperr2:Double?
var plntransdeplim:Int?
var plntransdepstr:String?
var plnradj:Double?
var plnradjerr1:Double?
var plnradjerr2:Double?
var plnradjlim:Int?
var plnradjstr:String?
var plnratror:Double?
var plnratrorerr1:Double?
var plnratrorerr2:Double?
var plnratrorlim:Int?
var plnratrorstr:String?
var plntranmid:Double?
var plntranmiderr1:Double?
var plntranmiderr2:Double?
var plntranmidlim:Int?
var plntranmidstr:String?
var facility:String?
var instrument:String?
var rowupdate:String?
var plntname:String?
var plntranreflink:String?
}

public struct EmissionspecResponse:Codable {
var centralwavelng:Double?
var bandwidth:Double?
var especlipdep:Double?
var especlipdeperr1:Double?
var especlipdeperr2:Double?
var especlipdeplim:Int?
var especlipdepstr:String?
var espbritemp:Int?
var espbritemperr1:Int?
var espbritemperr2:Int?
var espbritemplim:Int?
var espbritempstr:String?
var facility:String?
var instrument:String?
var rowupdate:String?
var plntname:String?
var note:String?
var plntreflink:String?
}

public struct PsResponse:Codable {
var pl_name:String?
var pl_letter:String?
var hostname:String?
var hd_name:String?
var hip_name:String?
var tic_id:String?
var default_flag:Int?
var pl_refname:String?
var st_refname:String?
var sy_refname:String?
var disc_pubdate:String?
var disc_year:Int?
var discoverymethod:String?
var disc_locale:String?
var disc_facility:String?
var disc_instrument:String?
var disc_telescope:String?
var disc_refname:String?
var ra:Double?
var rastr:String?
var dec:Double?
var decstr:String?
var glon:Double?
var glat:Double?
var elon:Double?
var elat:Double?
var pl_orbper:Double?
var pl_orbpererr1:Double?
var pl_orbpererr2:Double?
var pl_orbperlim:Int?
var pl_orbperstr:String?
var pl_orblpererr1:Double?
var pl_orblper:Double?
var pl_orblpererr2:Double?
var pl_orblperlim:Int?
var pl_orblperstr:String?
var pl_orbsmax:Double?
var pl_orbsmaxerr1:Double?
var pl_orbsmaxerr2:Double?
var pl_orbsmaxlim:Int?
var pl_orbsmaxstr:String?
var pl_orbincl:Double?
var pl_orbinclerr1:Double?
var pl_orbinclerr2:Double?
var pl_orbincllim:Int?
var pl_orbinclstr:String?
var pl_orbtper:Double?
var pl_orbtpererr1:Double?
var pl_orbtpererr2:Double?
var pl_orbtperlim:Int?
var pl_orbtperstr:String?
var pl_orbeccen:Double?
var pl_orbeccenerr1:Double?
var pl_orbeccenerr2:Double?
var pl_orbeccenlim:Int?
var pl_orbeccenstr:String?
var pl_eqt:Double?
var pl_eqterr1:Double?
var pl_eqterr2:Double?
var pl_eqtlim:Int?
var pl_eqtstr:String?
var pl_occdep:Double?
var pl_occdeperr1:Double?
var pl_occdeperr2:Double?
var pl_occdeplim:Int?
var pl_occdepstr:String?
var pl_insol:Double?
var pl_insolerr1:Double?
var pl_insolerr2:Double?
var pl_insollim:Int?
var pl_insolstr:String?
var pl_dens:Double?
var pl_denserr1:Double?
var pl_denserr2:Double?
var pl_denslim:Int?
var pl_densstr:String?
var pl_trandep:Double?
var pl_trandeperr1:Double?
var pl_trandeperr2:Double?
var pl_trandeplim:Int?
var pl_trandepstr:String?
var pl_tranmid:Double?
var pl_tranmiderr1:Double?
var pl_tranmiderr2:Double?
var pl_tranmidlim:Int?
var pl_tranmidstr:String?
var pl_trandur:Double?
var pl_trandurerr1:Double?
var pl_trandurerr2:Double?
var pl_trandurlim:Int?
var pl_trandurstr:String?
var pl_rvamp:Double?
var pl_rvamperr1:Double?
var pl_rvamperr2:Double?
var pl_rvamplim:Int?
var pl_rvampstr:String?
var pl_radj:Double?
var pl_radjerr1:Double?
var pl_radjerr2:Double?
var pl_radjlim:Int?
var pl_radjstr:String?
var pl_rade:Double?
var pl_radeerr1:Double?
var pl_radeerr2:Double?
var pl_radelim:Int?
var pl_radestr:String?
var pl_ratror:Double?
var pl_ratrorerr1:Double?
var pl_ratrorerr2:Double?
var pl_ratrorlim:Int?
var pl_ratrorstr:String?
var pl_ratdor:Double?
var pl_ratdorerr1:Double?
var pl_ratdorerr2:Double?
var pl_ratdorlim:Int?
var pl_ratdorstr:String?
var pl_imppar:Double?
var pl_impparerr1:Double?
var pl_impparerr2:Double?
var pl_impparlim:Int?
var pl_impparstr:String?
var pl_cmassj:Double?
var pl_cmassjerr1:Double?
var pl_cmassjerr2:Double?
var pl_cmassjlim:Int?
var pl_cmassjstr:String?
var pl_cmasse:Double?
var pl_cmasseerr1:Double?
var pl_cmasseerr2:Double?
var pl_cmasselim:Int?
var pl_cmassestr:String?
var pl_massj:Double?
var pl_massjerr1:Double?
var pl_massjerr2:Double?
var pl_massjlim:Int?
var pl_massjstr:String?
var pl_masse:Double?
var pl_masseerr1:Double?
var pl_masseerr2:Double?
var pl_masselim:Int?
var pl_massestr:String?
var pl_bmassj:Double?
var pl_bmassjerr1:Double?
var pl_bmassjerr2:Double?
var pl_bmassjlim:Int?
var pl_bmassjstr:String?
var pl_bmasse:Double?
var pl_bmasseerr1:Double?
var pl_bmasseerr2:Double?
var pl_bmasselim:Int?
var pl_bmassestr:String?
var pl_bmassprov:String?
var pl_msinij:Double?
var pl_msinijerr1:Double?
var pl_msinijerr2:Double?
var pl_msinijlim:Int?
var pl_msinijstr:String?
var pl_msinie:Double?
var pl_msinieerr1:Double?
var pl_msinieerr2:Double?
var pl_msinielim:Int?
var pl_msiniestr:String?
var st_teff:Double?
var st_tefferr1:Double?
var st_tefferr2:Double?
var st_tefflim:Int?
var st_teffstr:String?
var st_met:Double?
var st_meterr1:Double?
var st_meterr2:Double?
var st_metlim:Int?
var st_metstr:String?
var st_radv:Double?
var st_radverr1:Double?
var st_radverr2:Double?
var st_radvlim:Int?
var st_radvstr:String?
var st_vsin:Double?
var st_vsinerr1:Double?
var st_vsinerr2:Double?
var st_vsinlim:Int?
var st_vsinstr:String?
var st_lum:Double?
var st_lumerr1:Double?
var st_lumerr2:Double?
var st_lumlim:Int?
var st_lumstr:String?
var st_logg:Double?
var st_loggerr1:Double?
var st_loggerr2:Double?
var st_logglim:Int?
var st_loggstr:String?
var st_age:Double?
var st_ageerr1:Double?
var st_ageerr2:Double?
var st_agelim:Int?
var st_agestr:String?
var st_mass:Double?
var st_masserr1:Double?
var st_masserr2:Double?
var st_masslim:Int?
var st_massstr:String?
var st_dens:Double?
var st_denserr1:Double?
var st_denserr2:Double?
var st_denslim:Int?
var st_densstr:String?
var st_rad:Double?
var st_raderr1:Double?
var st_raderr2:Double?
var st_radlim:Int?
var st_radstr:String?
var ttv_flag:Int?
var ptv_flag:Int?
var tran_flag:Int?
var rv_flag:Int?
var ast_flag:Int?
var obm_flag:Int?
var micro_flag:Int?
var etv_flag:Int?
var ima_flag:Int?
var pul_flag:Int?
var soltype:String?
var sy_snum:Int?
var sy_pnum:Int?
var sy_mnum:Int?
var st_nphot:Int?
var st_nrvc:Int?
var st_nspec:Int?
var pl_nnotes:Int?
var pl_ntranspec:Int?
var pl_nespec:Int?
var pl_ndispec:Int?
var sy_pm:Double?
var sy_pmerr1:Double?
var sy_pmerr2:Double?
var sy_pmstr:String?
var sy_pmra:Double?
var sy_pmraerr1:Double?
var sy_pmraerr2:Double?
var sy_pmrastr:String?
var sy_pmdec:Double?
var sy_pmdecerr1:Double?
var sy_pmdecerr2:Double?
var sy_pmdecstr:String?
var sy_plx:Double?
var sy_plxerr1:Double?
var sy_plxerr2:Double?
var sy_plxstr:String?
var sy_dist:Double?
var sy_disterr1:Double?
var sy_disterr2:Double?
var sy_diststr:String?
var sy_bmag:Double?
var sy_bmagerr1:Double?
var sy_bmagerr2:Double?
var sy_bmagstr:String?
var sy_vmag:Double?
var sy_vmagerr1:Double?
var sy_vmagerr2:Double?
var sy_vmagstr:String?
var sy_jmag:Double?
var sy_jmagerr1:Double?
var sy_jmagerr2:Double?
var sy_jmagstr:String?
var sy_hmag:Double?
var sy_hmagerr1:Double?
var sy_hmagerr2:Double?
var sy_hmagstr:String?
var sy_kmag:Double?
var sy_kmagerr1:Double?
var sy_kmagerr2:Double?
var sy_kmagstr:String?
var sy_umag:Double?
var sy_umagerr1:Double?
var sy_umagerr2:Double?
var sy_umagstr:String?
var sy_rmag:Double?
var sy_rmagerr1:Double?
var sy_rmagerr2:Double?
var sy_rmagstr:String?
var sy_imag:Double?
var sy_imagerr1:Double?
var sy_imagerr2:Double?
var sy_imagstr:String?
var sy_zmag:Double?
var sy_zmagerr1:Double?
var sy_zmagerr2:Double?
var sy_zmagstr:String?
var sy_w1mag:Double?
var sy_w1magerr1:Double?
var sy_w1magerr2:Double?
var sy_w1magstr:String?
var sy_w2mag:Double?
var sy_w2magerr1:Double?
var sy_w2magerr2:Double?
var sy_w2magstr:String?
var sy_w3mag:Double?
var sy_w3magerr1:Double?
var sy_w3magerr2:Double?
var sy_w3magstr:String?
var sy_w4mag:Double?
var sy_w4magerr1:Double?
var sy_w4magerr2:Double?
var sy_w4magstr:String?
var sy_gmag:Double?
var sy_gmagerr1:Double?
var sy_gmagerr2:Double?
var sy_gmagstr:String?
var sy_gaiamag:Double?
var sy_gaiamagerr1:Double?
var sy_gaiamagerr2:Double?
var sy_gaiamagstr:String?
var sy_tmag:Double?
var sy_tmagerr1:Double?
var sy_tmagerr2:Double?
var sy_tmagstr:String?
var pl_controv_flag:Int?
var pl_tsystemref:String?
var st_metratio:String?
var st_spectype:String?
var sy_kepmag:Double?
var sy_kepmagerr1:Double?
var sy_kepmagerr2:Double?
var sy_kepmagstr:String?
var st_rotp:Double?
var st_rotperr1:Double?
var st_rotperr2:Double?
var st_rotplim:Int?
var st_rotpstr:String?
var pl_projobliq:Double?
var pl_projobliqerr1:Double?
var pl_projobliqerr2:Double?
var pl_projobliqlim:Int?
var pl_projobliqstr:String?
var x:Double?
var pl_trueobliq:Double?
var pl_trueobliqerr1:Double?
var y:Double?
var z:Double?
var pl_trueobliqerr2:Double?
var htm20:Int?
var pl_trueobliqlim:Int?
var gaia_id:String?
var cb_flag:Int?
var pl_trueobliqstr:String?
var sy_icmag:Double?
var sy_icmagerr1:Double?
var sy_icmagerr2:Double?
var sy_icmagstr:String?
var rowupdate:String?
var pl_pubdate:String?
var releasedate:String?
var dkin_flag:Int?
}

public struct KeplernamesResponse:Codable {
var kepid:String?
var pl_name:String?
var koi_name:String?
var kepler_name:String?
}

public struct K2namesResponse:Codable {
var k2_name:String?
var pl_name:String?
var epic_id:String?
}

public struct ToiResponse:Codable {
var tid:Int?
var toi:String?
var toipfx:String?
var ctoi_alias:String?
var pl_pnum:Int?
var tfopwg_disp:String?
var st_tmag:Double?
var st_tmagerr1:Double?
var st_tmagerr2:Double?
var st_tmagsymerr:Int?
var st_tmaglim:Int?
var ra:Double?
var raerr1:Double?
var raerr2:Double?
var rasymerr:Int?
var rastr:String?
var dec:Double?
var decerr1:Double?
var decerr2:Double?
var decsymerr:Int?
var decstr:String?
var st_pmra:Double?
var st_pmraerr1:Double?
var st_pmraerr2:Double?
var st_pmrasymerr:Int?
var st_pmralim:Int?
var st_pmdec:Double?
var st_pmdecerr1:Double?
var st_pmdecerr2:Double?
var st_pmdecsymerr:Int?
var st_pmdeclim:Int?
var pl_tranmid:Double?
var pl_tranmiderr1:Double?
var pl_tranmiderr2:Double?
var pl_tranmidsymerr:Int?
var pl_tranmidlim:Int?
var pl_orbper:Double?
var pl_orbpererr1:Double?
var pl_orbpererr2:Double?
var pl_orbpersymerr:Int?
var pl_orbperlim:Int?
var pl_trandurh:Double?
var pl_trandurherr1:Double?
var pl_trandurherr2:Double?
var pl_trandurhsymerr:Int?
var pl_trandurhlim:Int?
var pl_trandep:Double?
var pl_trandeperr1:Double?
var pl_trandeperr2:Double?
var pl_trandepsymerr:Int?
var pl_trandeplim:Int?
var pl_rade:Double?
var pl_radeerr1:Double?
var pl_radeerr2:Double?
var pl_radesymerr:Int?
var pl_radelim:Int?
var pl_insol:Double?
var pl_insolerr1:Double?
var pl_insolerr2:Double?
var pl_insolsymerr:Int?
var pl_insollim:Int?
var pl_eqt:Double?
var pl_eqterr1:Double?
var pl_eqterr2:Double?
var pl_eqtsymerr:Int?
var pl_eqtlim:Int?
var st_dist:Double?
var st_disterr1:Double?
var st_disterr2:Double?
var st_distsymerr:Int?
var st_distlim:Int?
var st_teff:Double?
var st_tefferr1:Double?
var st_tefferr2:Double?
var st_teffsymerr:Int?
var st_tefflim:Int?
var st_logg:Double?
var st_loggerr1:Double?
var st_loggerr2:Double?
var st_loggsymerr:Int?
var st_logglim:Int?
var st_rad:Double?
var st_raderr1:Double?
var st_raderr2:Double?
var st_radsymerr:Int?
var st_radlim:Int?
var sectors:String?
var toi_created:String?
var rowupdate:String?
var release_date:String?
}

public struct UkirttimeseriesResponse:Codable {
var sourceid:String?
var phot_method:String?
var obs_year:Int?
var bulge:String?
var field:Int?
var ccdid:Int?
var hjdstart:Double?
var hjdstop:Double?
var hjd_ref:Double?
var ra:Double?
var dec:Double?
var h_mag:Double?
var j_mag:Double?
var k_mag:Double?
var npts:Int?
var k2c9_flag:Int?
var ukirt_evt_flag:Int?
var ukirt_id:String?
var ogle_evt_flag:Int?
var ogle_id:String?
var moa_evt_flag:Int?
var moa_id:String?
var moa_star_id:String?
var statnpts:Int?
var minvalue:Double?
var maxvalue:Double?
var mean:Double?
var stddevwrtmean:Double?
var median:Double?
var stddevwrtmed:Double?
var n5sigma:Int?
var f5sigma:Double?
var medabsdev:Double?
var chisquared:Double?
var range595:Double?
var x:Double?
var y:Double?
var z:Double?
var spt_ind:Int?
}

public struct MlResponse:Codable {
var sy_hmag:Double?
var sy_hmaglim:Int?
var sy_hmagstr:String?
var ml_maghsdef:Int?
var ml_maghserr1:Double?
var ml_maghserr2:Double?
var ml_maghsformat:String?
var ml_maghslim:Int?
var ml_maghsodef:Int?
var ml_maghsoerr1:Double?
var ml_maghsoerr2:Double?
var ml_maghsoformat:String?
var ml_maghsolim:Int?
var ml_maghso:Double?
var ml_maghsostr:String?
var ml_maghs:Double?
var ml_maghsstr:String?
var ml_magibasedef:Int?
var ml_magibaseerr1:Double?
var ml_magibaseerr2:Double?
var ml_magibase:Double?
var ml_magibaseformat:String?
var ml_magibaselim:Int?
var ml_magibasestr:String?
var ml_magibl:Double?
var ml_magibldef:Int?
var ml_magiblerr1:Double?
var ml_magiblerr2:Double?
var ml_magiblformat:String?
var ml_magibllim:Int?
var ml_magiblstr:String?
var sy_icmagdef:Int?
var sy_icmagerr1:Double?
var sy_icmagerr2:Double?
var sy_icmagformat:String?
var sy_icmag:Double?
var sy_icmaglim:Int?
var sy_icmagstr:String?
var ml_magisdef:Int?
var ml_magiserr1:Double?
var ml_magiserr2:Double?
var ml_magisformat:String?
var ml_magislim:Int?
var ml_magisodef:Int?
var ml_magisoerr1:Double?
var ml_magisoerr2:Double?
var ml_magisoformat:String?
var ml_magisolim:Int?
var ml_magiso:Double?
var ml_magisostr:String?
var ml_magis:Double?
var ml_magisstr:String?
var sy_jmagdef:Int?
var sy_jmagerr1:Double?
var sy_jmagerr2:Double?
var sy_jmagformat:String?
var sy_jmag:Double?
var sy_jmaglim:Int?
var sy_jmagstr:String?
var ml_magjsdef:Int?
var ml_magjserr1:Double?
var ml_magjserr2:Double?
var ml_magjsformat:String?
var ml_extvflddef:Int?
var ml_extvflderr1:Double?
var ml_extvflderr2:Double?
var ml_extvfldformat:String?
var ml_extvfldlim:Int?
var ml_extvfld:Double?
var ml_extvfldstr:String?
var sy_hmagdef:Int?
var sy_hmagerr1:Double?
var sy_hmagerr2:Double?
var sy_hmagformat:String?
var ml_magjslim:Int?
var ml_magjsodef:Int?
var ml_magjsoerr1:Double?
var ml_magjsoerr2:Double?
var ml_magjsoformat:String?
var ml_magjsolim:Int?
var ml_magjso:Double?
var ml_magjsostr:String?
var ml_magjs:Double?
var ml_magjsstr:String?
var sy_kmagdef:Int?
var sy_kmagerr1:Double?
var sy_kmagerr2:Double?
var sy_kmagformat:String?
var sy_kmag:Double?
var sy_kmaglim:Int?
var sy_kmagstr:String?
var ml_magksdef:Int?
var ml_magkserr1:Double?
var ml_magkserr2:Double?
var ml_magksformat:String?
var ml_magkslim:Int?
var ml_magksodef:Int?
var ml_magksoerr1:Double?
var ml_magksoerr2:Double?
var ml_magksoformat:String?
var ml_magksolim:Int?
var ml_magkso:Double?
var ml_magksostr:String?
var ml_magks:Double?
var ml_magksstr:String?
var sy_vmagdef:Int?
var sy_vmagerr1:Double?
var sy_vmagerr2:Double?
var sy_vmagformat:String?
var sy_vmag:Double?
var sy_vmaglim:Int?
var sy_vmagstr:String?
var ml_magvsdef:Int?
var ml_magvserr1:Double?
var ml_magvserr2:Double?
var ml_magvsformat:String?
var ml_magvslim:Int?
var ml_magvsodef:Int?
var ml_magvsoerr1:Double?
var ml_magvsoerr2:Double?
var ml_magvsoformat:String?
var ml_magvsolim:Int?
var ml_magvso:Double?
var ml_magvsostr:String?
var ml_magvs:Double?
var ml_magvsstr:String?
var st_massdef:Int?
var st_masserr1:Double?
var st_masserr2:Double?
var st_massformat:String?
var st_mass:Double?
var st_masslim:Int?
var st_massstr:String?
var pl_massedef:Int?
var pl_masseerr1:Double?
var pl_masseerr2:Double?
var pl_masseformat:String?
var pl_masselim:Int?
var pl_masse:Double?
var pl_massestr:String?
var pl_massjdef:Int?
var pl_massjerr1:Double?
var pl_massjerr2:Double?
var pl_massjformat:String?
var pl_massjlim:Int?
var pl_massj:Double?
var pl_massjstr:String?
var ml_massratiodef:Int?
var ml_massratioerr1:Double?
var ml_massratioerr2:Double?
var ml_massratioformat:String?
var ml_massratiolim:Int?
var ml_massratio:Double?
var ml_massratiostr:String?
var ml_modelchisq:Double?
var ml_modeldef:Int?
var ml_plxmicrodef:Int?
var ml_plxmicroedef:Int?
var ml_plxmicroeerr1:Double?
var ml_plxmicroeerr2:Double?
var ml_plxmicroeformat:String?
var ml_plxmicroelim:Int?
var ml_plxmicroe:Double?
var ml_plxmicroerr1:Double?
var ml_plxmicroerr2:Double?
var ml_plxmicroestr:String?
var ml_plxmicroformat:String?
var ml_plxmicrolim:Int?
var ml_plxmicro:Double?
var ml_plxmicrondef:Int?
var ml_plxmicronerr1:Double?
var ml_plxmicronerr2:Double?
var ml_plxmicronformat:String?
var ml_plxmicronlim:Int?
var ml_plxmicron:Double?
var ml_plxmicronstr:String?
var ml_plxmicrostr:String?
var ml_plxreldef:Int?
var ml_plxrelerr1:Double?
var ml_plxrelerr2:Double?
var ml_plxrelformat:String?
var ml_plxrel:Double?
var ml_plxrellim:Int?
var ml_plxrelstr:String?
var ml_pmrellsdef:Int?
var ml_pmrellserr1:Double?
var ml_pmrellserr2:Double?
var ml_pmrellsformat:String?
var ml_pmrells:Double?
var ml_pmrellslim:Int?
var ml_pmrellsstr:String?
var ml_pmsdef:Int?
var ml_pmserr1:Double?
var ml_pmserr2:Double?
var ml_pmsformat:String?
var ml_pmslim:Int?
var ml_pms:Double?
var ml_pmsstr:String?
var ml_radeinang:Double?
var ml_radeinangdef:Int?
var ml_radeinangerr1:Double?
var ml_radeinangerr2:Double?
var ml_radeinangformat:String?
var ml_radeinanglim:Int?
var ml_radeinangstr:String?
var ml_radsangdef:Int?
var ml_radsangerr1:Double?
var ml_radsangerr2:Double?
var ml_radsangformat:String?
var ml_radsanglim:Int?
var ml_radsang:Double?
var ml_radsangstr:String?
var ml_radsnormdef:Int?
var ml_radsnormerr1:Double?
var ml_radsnormerr2:Double?
var ml_radsnormformat:String?
var ml_radsnormlim:Int?
var ml_radsnorm:Double?
var ml_radsnormstr:String?
var ml_radsphydef:Int?
var ml_radsphyerr1:Double?
var ml_radsphyerr2:Double?
var ml_radsphyformat:String?
var ml_radsphylim:Int?
var ml_radsphy:Double?
var ml_radsphystr:String?
var ml_redhkdef:Int?
var ml_redhkerr1:Double?
var ml_redhkerr2:Double?
var ml_redhkformat:String?
var ml_redhklim:Int?
var ml_redhk:Double?
var ml_redhkstr:String?
var ml_redvidef:Int?
var ml_redvierr1:Double?
var ml_redvierr2:Double?
var ml_redviformat:String?
var ml_redvilim:Int?
var ml_redvi:Double?
var ml_redvistr:String?
var ml_redvkdef:Int?
var ml_redvkerr1:Double?
var ml_redvkerr2:Double?
var ml_redvkformat:String?
var ml_redvklim:Int?
var ml_redvk:Double?
var ml_redvkstr:String?
var pl_solnid:String?
var st_solnid:String?
var sy_solnid:String?
var ml_solnid:String?
var ml_sepinsnorpdef:Int?
var ml_sepinsnorperr1:Double?
var ml_sepinsnorperr2:Double?
var ml_sepinsnorpformat:String?
var ml_sepinsnorplim:Int?
var ml_sepinsnorp:Double?
var ml_sepinsnorpstr:String?
var ml_sepminflag:Int?
var ml_sepminnormdef:Int?
var ml_sepminnormerr1:Double?
var ml_sepminnormerr2:Double?
var ml_sepminnormformat:String?
var ml_sepminnormlim:Int?
var ml_sepminnorm:Double?
var ml_sepminnormstr:String?
var pl_orbsmaxdef:Int?
var pl_orbsmaxerr1:Double?
var pl_orbsmaxerr2:Double?
var pl_orbsmaxformat:String?
var pl_orbsmaxlim:Int?
var pl_orbsmax:Double?
var pl_orbsmaxstr:String?
var ml_tsepmindef:Int?
var ml_tsepminerr1:Double?
var ml_tsepminerr2:Double?
var ml_tsepminformat:String?
var ml_tsepminlim:Int?
var ml_tsepminstr:String?
var ml_tsepmin:Double?
var ml_xtimeeindef:Int?
var ml_xtimeein:Double?
var ml_xtimeeinerr1:Double?
var ml_xtimeeinerr2:Double?
var ml_xtimeeinformat:String?
var ml_xtimeeinlim:Int?
var ml_xtimeeinstr:String?
var ml_xtimesrcdef:Int?
var ml_xtimesrcerr1:Double?
var ml_xtimesrcerr2:Double?
var ml_xtimesrcformat:String?
var ml_xtimesrclim:Int?
var ml_xtimesrc:Double?
var ml_xtimesrcstr:String?
var pl_name:String?
var htmllink:String?
var ra:Double?
var rastr:String?
var rowupdate:String?
var spt_ind:Int?
var x:Double?
var y:Double?
var z:Double?
var dec:Double?
var decstr:String?
var glat:Double?
var glon:Double?
var ml_angstlaxdef:Int?
var ml_angstlaxerr1:Double?
var ml_angstlaxerr2:Double?
var ml_angstlaxformat:String?
var ml_angstlaxlim:Int?
var ml_angstlax:Double?
var ml_angstlaxstr:String?
var cb_flag:Int?
var ml_colhksdef:Int?
var ml_colhkserr1:Double?
var ml_colhkserr2:Double?
var ml_colhksformat:String?
var ml_colhkslim:Int?
var ml_colhksodef:Int?
var ml_colhksoerr1:Double?
var ml_colhksoerr2:Double?
var ml_colhksoformat:String?
var ml_colhksolim:Int?
var ml_colhkso:Double?
var ml_colhksostr:String?
var ml_colhks:Double?
var ml_colhksstr:String?
var ml_colihsdef:Int?
var ml_colihserr1:Double?
var ml_colihserr2:Double?
var ml_colihsformat:String?
var ml_colihslim:Int?
var ml_colihsodef:Int?
var ml_colihsoerr1:Double?
var ml_colihsoerr2:Double?
var ml_colihsoformat:String?
var ml_colihsolim:Int?
var ml_colihso:Double?
var ml_colihsostr:String?
var ml_colihs:Double?
var ml_colihsstr:String?
var ml_colvibl:Double?
var ml_colvibldef:Int?
var ml_colviblerr1:Double?
var ml_colviblerr2:Double?
var ml_colviblformat:String?
var ml_colvibllim:Int?
var ml_colviblstr:String?
var ml_colvisdef:Int?
var ml_colviserr1:Double?
var ml_colviserr2:Double?
var ml_colvisformat:String?
var ml_colvislim:Int?
var ml_colvisodef:Int?
var ml_colvisoerr1:Double?
var ml_colvisoerr2:Double?
var ml_colvisoformat:String?
var ml_colvisolim:Int?
var ml_colviso:Double?
var ml_colvisostr:String?
var ml_colvis:Double?
var ml_colvisstr:String?
var ml_colvksdef:Int?
var ml_colvkserr1:Double?
var ml_colvkserr2:Double?
var ml_colvksformat:String?
var ml_colvkslim:Int?
var ml_colvksodef:Int?
var ml_colvksoerr1:Double?
var ml_colvksoerr2:Double?
var ml_colvksoformat:String?
var ml_colvksolim:Int?
var ml_colvkso:Double?
var ml_colvksostr:String?
var ml_colvks:Double?
var ml_colvksstr:String?
var ml_dalphadtdef:Int?
var ml_dalphadterr1:Double?
var ml_dalphadterr2:Double?
var ml_dalphadtformat:String?
var ml_dalphadtlim:Int?
var ml_dalphadt:Double?
var ml_dalphadtstr:String?
var ml_description:String?
var sy_distdef:Int?
var sy_disterr1:Double?
var sy_disterr2:Double?
var sy_distformat:String?
var sy_dist:Double?
var sy_distlim:Int?
var sy_diststr:String?
var ml_distsdef:Int?
var ml_distserr1:Double?
var ml_distserr2:Double?
var ml_distsformat:String?
var ml_distslim:Int?
var ml_dists:Double?
var ml_distsstr:String?
var ml_dsdtdef:Int?
var ml_dsdterr1:Double?
var ml_dsdterr2:Double?
var ml_dsdtformat:String?
var ml_dsdtlim:Int?
var ml_dsdt:Double?
var ml_dsdtstr:String?
var ml_efftimedef:Int?
var ml_efftime:Double?
var ml_efftimeerr1:Double?
var ml_efftimeerr2:Double?
var ml_efftimeformat:String?
var ml_efftimelim:Int?
var ml_efftimestr:String?
var ml_exthflddef:Int?
var ml_exthflderr1:Double?
var ml_exthflderr2:Double?
var ml_exthfldformat:String?
var ml_exthfldlim:Int?
var ml_exthfld:Double?
var ml_exthfldstr:String?
var ml_extiflddef:Int?
var ml_extiflderr1:Double?
var ml_extiflderr2:Double?
var ml_extifldformat:String?
var ml_extifldlim:Int?
var ml_extifld:Double?
var ml_extifldstr:String?
var ml_extjflddef:Int?
var ml_extjflderr1:Double?
var ml_extjflderr2:Double?
var ml_extjfldformat:String?
var ml_extjfldlim:Int?
var ml_extjfld:Double?
var ml_extjfldstr:String?
var ml_extkflddef:Int?
var ml_extkflderr1:Double?
var ml_extkflderr2:Double?
var ml_extkfldformat:String?
var ml_extkfldlim:Int?
var ml_extkfld:Double?
var ml_extkfldstr:String?
}

public struct Object_aliasesResponse:Codable {
var resolved_name:String?
}

public struct K2pandcResponse:Codable {
var sy_gmagstr:String?
var sy_gaiamag:Double?
var sy_gaiamagerr1:Double?
var sy_gaiamagerr2:Double?
var sy_gaiamagstr:String?
var sy_tmag:Double?
var sy_tmagerr1:Double?
var sy_tmagerr2:Double?
var sy_tmagstr:String?
var pl_controv_flag:Int?
var pl_tsystemref:String?
var st_metratio:String?
var st_spectype:String?
var sy_kepmag:Double?
var sy_kepmagerr1:Double?
var sy_kepmagerr2:Double?
var sy_kepmagstr:String?
var st_rotp:Double?
var st_rotperr1:Double?
var st_rotperr2:Double?
var st_rotplim:Int?
var st_rotpstr:String?
var pl_projobliq:Double?
var pl_projobliqerr1:Double?
var pl_projobliqerr2:Double?
var pl_projobliqlim:Int?
var pl_projobliqstr:String?
var x:Double?
var pl_trueobliq:Double?
var y:Double?
var pl_trueobliqerr1:Double?
var z:Double?
var pl_trueobliqerr2:Double?
var htm20:Int?
var gaia_id:String?
var pl_trueobliqlim:Int?
var cb_flag:Int?
var pl_trueobliqstr:String?
var sy_icmag:Double?
var sy_icmagerr1:Double?
var sy_icmagerr2:Double?
var sy_icmagstr:String?
var rowupdate:String?
var pl_pubdate:String?
var releasedate:String?
var dkin_flag:Int?
var pl_name:String?
var pl_letter:String?
var hostname:String?
var hd_name:String?
var epic_candname:String?
var epic_hostname:String?
var k2_name:String?
var hip_name:String?
var tic_id:String?
var default_flag:Int?
var pl_refname:String?
var st_refname:String?
var sy_refname:String?
var disc_pubdate:String?
var disc_year:Int?
var discoverymethod:String?
var disc_locale:String?
var disc_facility:String?
var disp_refname:String?
var disposition:String?
var k2_campaigns:String?
var k2_campaigns_num:Int?
var disc_instrument:String?
var disc_telescope:String?
var disc_refname:String?
var ra:Double?
var rastr:String?
var dec:Double?
var decstr:String?
var glon:Double?
var glat:Double?
var elon:Double?
var elat:Double?
var pl_orbper:Double?
var pl_orbpererr1:Double?
var pl_orbpererr2:Double?
var pl_orbperlim:Int?
var pl_orbperstr:String?
var pl_orblpererr1:Double?
var pl_orblper:Double?
var pl_orblpererr2:Double?
var pl_orblperlim:Int?
var pl_orblperstr:String?
var pl_orbsmax:Double?
var pl_orbsmaxerr1:Double?
var pl_orbsmaxerr2:Double?
var pl_orbsmaxlim:Int?
var pl_orbsmaxstr:String?
var pl_orbincl:Double?
var pl_orbinclerr1:Double?
var pl_orbinclerr2:Double?
var pl_orbincllim:Int?
var pl_orbinclstr:String?
var pl_orbtper:Double?
var pl_orbtpererr1:Double?
var pl_orbtpererr2:Double?
var pl_orbtperlim:Int?
var pl_orbtperstr:String?
var pl_orbeccen:Double?
var pl_orbeccenerr1:Double?
var pl_orbeccenerr2:Double?
var pl_orbeccenlim:Int?
var pl_orbeccenstr:String?
var pl_eqt:Double?
var pl_eqterr1:Double?
var pl_eqterr2:Double?
var pl_eqtlim:Int?
var pl_eqtstr:String?
var pl_occdep:Double?
var pl_occdeperr1:Double?
var pl_occdeperr2:Double?
var pl_occdeplim:Int?
var pl_occdepstr:String?
var pl_insol:Double?
var pl_insolerr1:Double?
var pl_insolerr2:Double?
var pl_insollim:Int?
var pl_insolstr:String?
var pl_dens:Double?
var pl_denserr1:Double?
var pl_denserr2:Double?
var pl_denslim:Int?
var pl_densstr:String?
var pl_trandep:Double?
var pl_trandeperr1:Double?
var pl_trandeperr2:Double?
var pl_trandeplim:Int?
var pl_trandepstr:String?
var pl_tranmid:Double?
var pl_tranmiderr1:Double?
var pl_tranmiderr2:Double?
var pl_tranmidlim:Int?
var pl_tranmidstr:String?
var pl_trandur:Double?
var pl_trandurerr1:Double?
var pl_trandurerr2:Double?
var pl_trandurlim:Int?
var pl_trandurstr:String?
var pl_rvamp:Double?
var pl_rvamperr1:Double?
var pl_rvamperr2:Double?
var pl_rvamplim:Int?
var pl_rvampstr:String?
var pl_radj:Double?
var pl_radjerr1:Double?
var pl_radjerr2:Double?
var pl_radjlim:Int?
var pl_radjstr:String?
var pl_rade:Double?
var pl_radeerr1:Double?
var pl_radeerr2:Double?
var pl_radelim:Int?
var pl_radestr:String?
var pl_ratror:Double?
var pl_ratrorerr1:Double?
var pl_ratrorerr2:Double?
var pl_ratrorlim:Int?
var pl_ratrorstr:String?
var pl_ratdor:Double?
var pl_ratdorerr1:Double?
var pl_ratdorerr2:Double?
var pl_ratdorlim:Int?
var pl_ratdorstr:String?
var pl_imppar:Double?
var pl_impparerr1:Double?
var pl_impparerr2:Double?
var pl_impparlim:Int?
var pl_impparstr:String?
var pl_cmassj:Double?
var pl_cmassjerr1:Double?
var pl_cmassjerr2:Double?
var pl_cmassjlim:Int?
var pl_cmassjstr:String?
var pl_cmasse:Double?
var pl_cmasseerr1:Double?
var pl_cmasseerr2:Double?
var pl_cmasselim:Int?
var pl_cmassestr:String?
var pl_massj:Double?
var pl_massjerr1:Double?
var pl_massjerr2:Double?
var pl_massjlim:Int?
var pl_massjstr:String?
var pl_masse:Double?
var pl_masseerr1:Double?
var pl_masseerr2:Double?
var pl_masselim:Int?
var pl_massestr:String?
var pl_bmassj:Double?
var pl_bmassjerr1:Double?
var pl_bmassjerr2:Double?
var pl_bmassjlim:Int?
var pl_bmassjstr:String?
var pl_bmasse:Double?
var pl_bmasseerr1:Double?
var pl_bmasseerr2:Double?
var pl_bmasselim:Int?
var pl_bmassestr:String?
var pl_bmassprov:String?
var pl_msinij:Double?
var pl_msinijerr1:Double?
var pl_msinijerr2:Double?
var pl_msinijlim:Int?
var pl_msinijstr:String?
var pl_msinie:Double?
var pl_msinieerr1:Double?
var pl_msinieerr2:Double?
var pl_msinielim:Int?
var pl_msiniestr:String?
var st_teff:Double?
var st_tefferr1:Double?
var st_tefferr2:Double?
var st_tefflim:Int?
var st_teffstr:String?
var st_met:Double?
var st_meterr1:Double?
var st_meterr2:Double?
var st_metlim:Int?
var st_metstr:String?
var st_radv:Double?
var st_radverr1:Double?
var st_radverr2:Double?
var st_radvlim:Int?
var st_radvstr:String?
var st_vsin:Double?
var st_vsinerr1:Double?
var st_vsinerr2:Double?
var st_vsinlim:Int?
var st_vsinstr:String?
var st_lum:Double?
var st_lumerr1:Double?
var st_lumerr2:Double?
var st_lumlim:Int?
var st_lumstr:String?
var st_logg:Double?
var st_loggerr1:Double?
var st_loggerr2:Double?
var st_logglim:Int?
var st_loggstr:String?
var st_age:Double?
var st_ageerr1:Double?
var st_ageerr2:Double?
var st_agelim:Int?
var st_agestr:String?
var st_mass:Double?
var st_masserr1:Double?
var st_masserr2:Double?
var st_masslim:Int?
var st_massstr:String?
var st_dens:Double?
var st_denserr1:Double?
var st_denserr2:Double?
var st_denslim:Int?
var st_densstr:String?
var st_rad:Double?
var st_raderr1:Double?
var st_raderr2:Double?
var st_radlim:Int?
var st_radstr:String?
var ttv_flag:Int?
var ptv_flag:Int?
var tran_flag:Int?
var rv_flag:Int?
var ast_flag:Int?
var obm_flag:Int?
var micro_flag:Int?
var etv_flag:Int?
var ima_flag:Int?
var pul_flag:Int?
var soltype:String?
var sy_snum:Int?
var sy_pnum:Int?
var sy_mnum:Int?
var st_nphot:Int?
var st_nrvc:Int?
var st_nspec:Int?
var pl_nespec:Int?
var pl_nnotes:Int?
var pl_ntranspec:Int?
var sy_pm:Double?
var sy_pmerr1:Double?
var sy_pmerr2:Double?
var sy_pmstr:String?
var sy_pmra:Double?
var sy_pmraerr1:Double?
var sy_pmraerr2:Double?
var sy_pmrastr:String?
var sy_pmdec:Double?
var sy_pmdecerr1:Double?
var sy_pmdecerr2:Double?
var sy_pmdecstr:String?
var sy_plx:Double?
var sy_plxerr1:Double?
var sy_plxerr2:Double?
var sy_plxstr:String?
var sy_dist:Double?
var sy_disterr1:Double?
var sy_disterr2:Double?
var sy_diststr:String?
var sy_bmag:Double?
var sy_bmagerr1:Double?
var sy_bmagerr2:Double?
var sy_bmagstr:String?
var sy_vmag:Double?
var sy_vmagerr1:Double?
var sy_vmagerr2:Double?
var sy_vmagstr:String?
var sy_jmag:Double?
var sy_jmagerr1:Double?
var sy_jmagerr2:Double?
var sy_jmagstr:String?
var sy_hmag:Double?
var sy_hmagerr1:Double?
var sy_hmagerr2:Double?
var sy_hmagstr:String?
var sy_kmag:Double?
var sy_kmagerr1:Double?
var sy_kmagerr2:Double?
var sy_kmagstr:String?
var sy_umag:Double?
var sy_umagerr1:Double?
var sy_umagerr2:Double?
var sy_umagstr:String?
var sy_rmag:Double?
var sy_rmagerr1:Double?
var sy_rmagerr2:Double?
var sy_rmagstr:String?
var sy_imag:Double?
var sy_imagerr1:Double?
var sy_imagerr2:Double?
var sy_imagstr:String?
var sy_zmag:Double?
var sy_zmagerr1:Double?
var sy_zmagerr2:Double?
var sy_zmagstr:String?
var sy_w1mag:Double?
var sy_w1magerr1:Double?
var sy_w1magerr2:Double?
var sy_w1magstr:String?
var sy_w2mag:Double?
var sy_w2magerr1:Double?
var sy_w2magerr2:Double?
var sy_w2magstr:String?
var sy_w3mag:Double?
var sy_w3magerr1:Double?
var sy_w3magerr2:Double?
var sy_w3magstr:String?
var sy_w4mag:Double?
var sy_w4magerr1:Double?
var sy_w4magerr2:Double?
var sy_w4magstr:String?
var sy_gmag:Double?
var sy_gmagerr1:Double?
var sy_gmagerr2:Double?
}

